### PR TITLE
Fixes #41 the resource reference returned from constructRestAPI

### LINKED ISSUE #41: Provider returns wrong field
### What happened?

https://github.com/pulumi/pulumi-java/pull/597

The field `deployment` contains wrong URN: 
`urn:pulumi:dev::iac-workshop-lambda-api-gateway::aws-apigateway:index:RestAPI::helloWorldApi` 

instead of:
`urn:pulumi:dev::iac-workshop-lambda-api-gateway::aws-apigateway:index:RestAPI$aws:apigateway/deployment:Deployment`

according to [schema](https://github.com/pulumi/pulumi-aws-apigateway/blob/main/schema.yaml#L406)

Java implementation is unable to deserialize this:
```
debug: Read response for resource: t=aws-apigateway:index:RestAPI, name=helloWorldApi, urn=urn:pulumi:dev::iac-workshop-lambda-api-gateway::aws-apigateway:index:RestAPI::helloWorldApi, id=, remote=true, data=fields {
      key: "api"
      value {
        struct_value {
          fields {
            key: "4dabf18193072939515e22adb298388d"
            value {
              string_value: "5cf8f73096256a8f31e491e813e4eb8e"
            }
          }
          fields {
            key: "id"
            value {
              string_value: ""
            }
          }
          fields {
            key: "urn"
            value {
              string_value: "urn:pulumi:dev::iac-workshop-lambda-api-gateway::aws-apigateway:index:RestAPI$aws:apigateway/restApi:RestApi::helloWorldApi"
            }
          }
        }
      }
    }
    fields {
      key: "deployment"
      value {
        struct_value {
          fields {
            key: "4dabf18193072939515e22adb298388d"
            value {
              string_value: "5cf8f73096256a8f31e491e813e4eb8e"
            }
          }
          fields {
            key: "urn"
            value {
              string_value: "urn:pulumi:dev::iac-workshop-lambda-api-gateway::aws-apigateway:index:RestAPI::helloWorldApi"
            }
          }
        }
      }
    }
    fields {
      key: "stage"
      value {
        struct_value {
          fields {
            key: "4dabf18193072939515e22adb298388d"
            value {
              string_value: "5cf8f73096256a8f31e491e813e4eb8e"
            }
          }
          fields {
            key: "id"
            value {
              string_value: ""
            }
          }
          fields {
            key: "urn"
            value {
              string_value: "urn:pulumi:dev::iac-workshop-lambda-api-gateway::aws-apigateway:index:RestAPI$aws:apigateway/stage:Stage::helloWorldApi"
            }
          }
        }
      }
    }
```

### Steps to reproduce

https://github.com/pulumi/pulumi-java/pull/597

### Expected Behavior

Getting a correct URN.

### Actual Behavior

Getting a wrong URN.

### Versions used

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
Fixes #41 

I am debugging pulumi/pulumi-java#594 and I have a repro program that works correctly after this fix. The following Java program fails to preview.  Peeking on the gRPC conversation happening during `pulumi preview` this is suspect:

```json
{
  "fullMethod": "/pulumirpc.ResourceMonitor/RegisterResource",
  "request": {
    "type": "aws-apigateway:index:RestAPI",
    "name": "helloWorldApi",
    "parent": "urn:pulumi:tdev::java-repro::pulumi:pulumi:Stack::java-repro-tdev",
    ...
  },
  "response": {
    "urn": "urn:pulumi:tdev::java-repro::aws-apigateway:index:RestAPI::helloWorldApi",
    "object": {
      "api": ....
      "deployment": {
        "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
        "urn": "urn:pulumi:tdev::java-repro::aws-apigateway:index:RestAPI::helloWorldApi"
      }, ...
    }
}
```

That is, the deployment prop returns a reference to helloWorldApi itself (see how it matches the urn in the response). This causes a type error in Java and C# since a reference to Deployment is expected instead.

With this change the problem is gone.

Listing:

```java
package myproject;

import com.pulumi.Pulumi;
import com.pulumi.asset.AssetArchive;
import com.pulumi.asset.StringAsset;
import com.pulumi.aws.iam.Role;
import com.pulumi.aws.iam.RoleArgs;
import com.pulumi.aws.iam.RolePolicyAttachment;
import com.pulumi.aws.iam.RolePolicyAttachmentArgs;
import com.pulumi.aws.iam.enums.ManagedPolicy;
import com.pulumi.aws.lambda.Function;
import com.pulumi.aws.lambda.FunctionArgs;
import com.pulumi.aws.lambda.enums.Runtime;
import com.pulumi.awsapigateway.RestAPI;
import com.pulumi.awsapigateway.RestAPIArgs;
import com.pulumi.awsapigateway.enums.Method;
import com.pulumi.awsapigateway.inputs.RouteArgs;

import java.util.Map;

public class App {

    public static void main(String[] args) {
        Pulumi.run(ctx -> {
            var role = new Role("lambdaRole", RoleArgs.builder()
                    .assumeRolePolicy("""
                            {
                              "Version": "2012-10-17",
                              "Statement": [
                                {
                                  "Effect": "Allow",
                                  "Principal": {
                                    "Service": "lambda.amazonaws.com"
                                  },
                                  "Action": "sts:AssumeRole"
                                }
                              ]
                            }""")
                    .build()
            );

            var lambdaBasicExecutionRole = new RolePolicyAttachment("basicExecutionRole", RolePolicyAttachmentArgs.builder()
                    .role(role.name())
                    .policyArn(ManagedPolicy.AWSLambdaBasicExecutionRole.getValue())
                    .build());

            var funcCode = new StringAsset("""
                                           exports.handler = async (event) => {
                                               return {
                                                   statusCode: 200,
                                                       body: "Hello, world!",
                                                       };
                                           }""");

            var func = new Function("helloWorldFunction",
                                    FunctionArgs.builder()
                                    .role(role.arn())
                                    .handler("index.handler")
                                    .runtime(Runtime.NodeJS12dX)
                                    .code(new AssetArchive(Map.of("index.js", funcCode)))
                                    .build());

            var api = new RestAPI("helloWorldApi", RestAPIArgs.builder()
                                  .routes(
                                          RouteArgs.builder()
                                          .path("/")
                                          .method(Method.GET)
                                          .eventHandler(func)
                                          .build()
                                          )
                                  .build());

        });
    }
}
```

### CODE REVIEW

**Review by stack72 — APPROVED** [review]
great catch!!!

File: provider/cmd/pulumi-resource-aws-apigateway/provider.ts [hunk 1]
```diff
@@ -43,7 +43,7 @@ async function constructRestAPI(name: string, inputs: pulumi.Inputs,
         state: {
             url: restAPI.url,
             api: restAPI.api,
-            deployment: restAPI,
+            deployment: restAPI.deployment,
```
Comment (pawelprazak) [inline provider/cmd/pulumi-resource-aws-apigateway/provider.ts:46]: great catch! I couldn't find it ;)
