### PR TITLE
Fix authorizer validation to enable reusing authorizers

### LINKED ISSUE #156: apigateway.RestAPI: Restricting multiple Authorizers
## Pulumi: apigateway.RestAPI restricting multiple authorizers to a unified authorizer across all routes. 

- Vote on this issue by adding a 👍 reaction

## Issue details

Multiple Authorizers issue in apigateway.RestAPI: I'm trying to create an API Gateway using "@pulumi/aws-apigateway" with the following code:

```bash

import { AuthorizerArgs } from "@pulumi/aws-apigateway/types/input";
import * as apigateway from "@pulumi/aws-apigateway";
import { authorizerLambda } from "./utils"

// Define the common authorizer
const commonAuthorizer: AuthorizerArgs = {
    parameterName: "Authorization",
    parameterLocation: "header",
    identityValidationExpression: "^Bearer [-0-9a-zA-Z._]*$",
    authType: "custom",
    type: "token",
    identitySource: ["method.request.header.Authorization"],
    handler: authorizerLambda,
    authorizerResultTtlInSeconds: 600,
};

// Create the API Gateway with routes
const api = new apigateway.RestAPI("test-api", {
    stageName: "v1",
    routes: [
        {
            path: "/route1",
            method: "PUT",
            eventHandler: route1PutLambdaFunction,
            authorizers: [commonAuthorizer],
        },
        {
            path: "/route1",
            method: "DELETE",
            eventHandler: route1DeleteLambdaFunction,
            authorizers: [commonAuthorizer],
        },
        {
            path: "/route2",
            method: "PUT",
            eventHandler: route2PutLambdaFunction,
            authorizers: [commonAuthorizer],
        },
        {
            path: "/route3",
            method: "PUT",
            eventHandler: route3PutLambdaFunction,
            authorizers: [commonAuthorizer],
        },
        // Add more routes as needed
    ],
});

```

### Affected area/feature

Issue: Even though I define a single commonAuthorizer, `pulumi up` creates a separate authorizer for each route. If there are 10 routes, it generates 10 different authorizers, roles, and permissions. This duplication causes exceed the default api gateway authorizers limit of 10.

Expected Behavior: It would be optimistic to find and release a workaround this, using `apigateway.RestAPI` and `routes: RouteArgs[]` with `authorizers: AuthorizerArgs[]` and a flexability to restrict it to a single reusable authorizer across all multiple routes.

Actual Behavior: Each route creates its own authorizer, resulting in unnecessary duplication of gateway authorizers, roles and permissions, and deployment hangs with more than 10 routes.

QA: Is there any currect workaround to address this?

### PR DESCRIPTION
**Pull request by flostadler**
This equality check here will never be truthy: https://github.com/pulumi/pulumi-aws-apigateway/blob/main/provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts#L1010
Those inputs come into the provider via GRPC and get re-assembled as objects, thus all authorizer always get different references. Even if their underlying values are equal.

fixes #156

### CODE REVIEW

File: provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts [hunk 1]
```diff
@@ -1003,16 +991,6 @@ function addAuthorizersToSwagger(
       auth.authorizerName || `${swagger.info.title}-authorizer-${suffix}`;
     auth.authorizerName = authName;
 
-    // Check API authorizers - if its a new authorizer add it to the apiAuthorizers
-    // if the name already exists, we check that the authorizer references the same authorizer
-    if (!apiAuthorizers[authName]) {
```
Comment (corymhall) [inline provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts:1008]: I worried about completely removing this validation. What is the behavior if there are two different authorizers that share the same name? Does one override the other?

Is there a way to do a partial check on the fields that that can be resolved? Or could we log a warning instead?

Comment (flostadler) [reply provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts:1008]: @corymhall I spent some more time trying to make the equality checks work. I found that nested resources don't get properly resolved by `apply`. I was able to workaround this by constructing an object out of the CustomResource (Lambda function in this case).
The validation works now.

File: provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts [hunk 2]
```diff
@@ -821,14 +833,104 @@ function createSwaggerSpec(
...
+): pulumi.Output<string | undefined> {
+  const namedAuthorizers: Record<string, Authorizer> = {};
+  const duplicates = authorizers.map((auth) => {
+    if (!auth.authorizerName) {
+      return undefined;
+    }
+
+    if (namedAuthorizers[auth.authorizerName]) {
+      return authorizerEquals(namedAuthorizers[auth.authorizerName], auth).apply((equal) => {
+        if (!equal) {
```
Comment (corymhall) [inline provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts:859]: How does this work? I would expect this to need to be 

```
if (equal) {
  return auth.authorizerName;
}
```

Because we want to return the name of the duplicate authorizer when they are equal right?

File: provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts [hunk 3]
```diff
@@ -821,14 +833,104 @@ function createSwaggerSpec(
...
+  });
+}
+
+/**
+ * Checks if two Authorizer objects are structurally equal.
+ * @param a - The first Authorizer object.
+ * @param b - The second Authorizer object.
+ * @returns A pulumi.Output<boolean> indicating whether the two Authorizer objects are equal.
+ */
+function authorizerEquals(
```
Comment (corymhall) [inline provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts:881]: Nice!

**Review by corymhall — CHANGES_REQUESTED** [review]
Just one question, otherwise looks great!

File: provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts (hunk 2 above)
Comment (flostadler) [reply provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts:859]: Maybe my naming here was a bit misleading. We're checking for authorizers that have the same name, but different configuration. I'm gonna add some more description to the docstring

Comment (flostadler) [reply provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts:860]: @corymhall I updated it. Let me know what you think

Comment (corymhall) [reply provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts:860]: ahh gotcha. I'm slow this morning 😀

**Review by corymhall — APPROVED** [review]
